vi2920va/FE_interview

FrontEnd/CORS.md

CORS와 동일출처 정책 설명 추가
설명을 추가했습니다.

[3주차][수민]Frontend - CORS

---

JavaScript/ArrayForEach-ArrayMap.md
JavaScript/Arrow-Function.md
JavaScript/README.md

- JavaScript - ArrowFunction
- JavaScript Arrow function과 this에 대해서 정리했습니다.
- JavaScript  Array.forEach vs Array.map에 대한 차이점을 정리했습니다.

[4주차][송현]JavaScript - ArrowFunction, Array.forEach VS Array.map

---

React/Ref-CallbackRef.md

React ref에 관한 내용 추가.
React에서 ref와 callback ref의 개념에 대한 설명을 추가했습니다.

[4주차][수민] React - Ref와 callback ref

---

FrontEnd/Webpack.md

모듈과 Webpack에 관한 설명 추가
모듈과 Webpack에 관한 설명 추가

[5주차][수민]Refactor: FrontEnd-Webpack 설명 추가

---

CSS/README.md
CSS/z-index.md
HTML/Doctype.md
HTML/README.md

- css - z-index
- html - doctype
html - doctype에 대해 정리해보았습니다.

[5주차][송현]css-z-index, html - doctype

---

TypeScript/Type&Interface.md

TypeScript - type&interface
type과 interface에대해 정리했습니다.

[6~7주차][영생]TypeScript - type&interface

---

Network/google.com을 치면 일어나는 일.md

[6~7주차][두현] Network - google.com을 치면 일어나는일

---

JavaScript/실행컨텍스트.md

[6~7주차][수민] JavaScript 실행 컨텍스트

---

JavaScript/Closure.md
React/React.useEffect-useLayoutEffect.md

React - useEffect VS useLayoutEffect
useEffect와 useLayoutEffect의 공통점과 차이점에 대한 내용입니다.

[6~7주차][남은] React - useEffect VS useLayoutEffect, JavaScript - Closure

---

JavaScript/Closure-example.md

JavaScript - Closure-example
JavaScript의 Closure 예시들을 정리하였습니다.

[8주차][남은] JavaScript - Closure-example

---

TypeScript/Generics.md

- TypeScript - Generics
- 타입스크립트 제네릭에 대해서 정리했습니다.

[9주차][영생]Add Typescript - Generics

---

JavaScript/Timer.md

*JavaScript - Timer
*JavaScript의 타이머와 관련있는 디바운스와 쓰로틀에 대하여 정리하였습니다.

[9주차][동기] Add:JavaScript - Timer

---

JavaScript/Prototype.md

[9주차][두현] JavaScript - Prototype

---

TypeScript/TypeAssertion.md

TypeScript : TypeAssertion vs TypeAnnotation 추가

[10주차][두현] TypeScript : TypeAssertion vs TypeAnnotation

---

GraphQL/GraphQL-Summary.md

[11주차][두현] GraphQL - Summary

---

JavaScript/이터러블과이터레이터.md

JavaScript - 이터러블과 이터레이터
JavaScript - 이터러블과 이터레이터 내용 추가
참여하지 않았지만 내용만 추가함

[12주차][남은] JavaScript - 이터러블과 이터레이터

---

TypeScript/Intersection.md

- TypeScript - Intersection
- TypeScript 인터섹션 공부중입니다

[송현][12주차]TypeScript - Intersection

---

TypeScript/UnionType.md

[송현] [13주차] TypeScript - Union Type

---

JavaScript/Class.md

JavaScript - Class
JavaScript - Class에 대한 내용을 추가했습니다.

[14주차] [남은] JavaScript - Class

---

React/React-router-dom.md

마크다운 형식 문제 수정
<> , 인라인 코드 등에서 마크다운이 인식하지 못하는 문제를 해결했습니다.

 [15주차] [주현] React - React-router-dom

---

JavaScript/프로토타입상속.md

JavaScript - 프로토타입 상속
JavaScript - 프로토타입 상속

[15주차] [남은] JavaScript - 프로토타입 상속

---

JavaScript/일급함수.md

Javascript - 일급함수

---

React/React-Test.md

[16주차] [수민] React - React Test 내용 추가

---

TypeScript/Types.md

[17주차] [수민] TypeScript - basic types

---

React/React-StateManagement.md

React - 상태관리(state management)
React의 상태관리의 필요성
React와 결합할 수 있는 상태관리 라이브러리의 종류를 비교

[18주차][주현] React - state management

---

TypeScript/Unkown-never-any.md

타입스크립트 타입 unknown/never/any의 비교
타입스크립트 타입 unknown/never/any의 비교

[18주차][수민] typescript: unknown/never/any

---

JavaScript/Intersection-Observer-API.md

Intersection Observer API
Intersection Observer API 관련 설명

[18주차][수민] JavaScript - Intersection Observer API
